import { Metadata } from "next";
import { Inter } from "next/font/google";
import LogginLayout from "./formRoot";
import "../../global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login Account",
  description: "Generated by create next app",
};

const FirstLogginLayout = ({ children }: { children: React.ReactNode }) => {
  return <LogginLayout/>;
};

export default FirstLogginLayout;
