import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../global.css'
import FirstStep from './formRoot';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Login Account',
    description: 'Generated by create next app',
};

const FirstIndexLayout = ({children}: {children: React.ReactNode}) => {
  return (
        <FirstStep/>
  );
};

export default FirstIndexLayout;