import { Metadata } from 'next';
import ThirdStep from './formRoot';
import { Inter } from 'next/font/google';
import '../../global.css'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Login Account',
  description: 'Generated by create next app',
};

const ThirdIndexLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ThirdStep />
  );
};

export default ThirdIndexLayout;