import { Metadata } from "next";
import { Inter } from "next/font/google";
import SecondLoggin from "./formRoot";
import "../../global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login Account",
  description: "Generated by create next app",
};

const SecondLogginLayout = ({ children }: { children: React.ReactNode }) => {
  return <SecondLoggin/>;
};

export default SecondLogginLayout;
